# SPDX-FileCopyrightText: 2019 Bitcoin Suisse
# SPDX-License-Identifier: LicenseRef-MIT-BitcoinSuisse

- package:
  - name: tzbtc
  - section:
    - name: exe:tzbtc
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude
  - section:
    - name: library
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude
  - section:
    - name: test:tzbtc-test
    - message:
      - name: Weeds exported
      - module:
        - name: Tree
        - identifier:
          - ingredients
          - main
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude
  - section:
    - name: exe:tzbtc-client
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude

