# SPDX-FileCopyrightText: 2019 Bitcoin Suisse
# SPDX-License-Identifier: LicenseRef-Proprietary

- package:
  - name: tzbtc
  - section:
    - name: test:tzbtc-test
    - message:
      - name: Weeds exported
      - module:
        - name: Tree
        - identifier:
          - ingredients
          - main

