# SPDX-FileCopyrightText: 2019 Bitcoin Suisse
#
# SPDX-License-Identifier: LicenseRef-Proprietary
#
<<: !include "./hpack/module.yaml"

name:                tzbtc
version:             0.1.1

extra-source-files:
- README.md
- CONTRIBUTING.md

category:            Blockchain
description: Wrapped Bitcoin on Tezos Blockchain

library:
  <<: *lib-common

  default-extensions:
    - DerivingStrategies
    - DeriveAnyClass
    - NoApplicativeDo

  dependencies:
    - aeson
    - aeson-casing
    - bytestring
    - containers
    - directory
    - hex-text
    - http-client
    - http-client-tls
    - http-types
    - fmt
    - morley
    - morley-ledgers
    - morley-prelude
    - morley-upgradeable
    - named
    - optparse-applicative
    - megaparsec
    - process
    - servant
    - servant-client
    - servant-client-core
    - singletons
    - text
    - tezos-bake-monitor-lib
    - universum
    - safe-exceptions
    - vector
    - vinyl
    - o-clock

executables:
  tzbtc:
    <<: *exec-common

    dependencies:
      - fmt
      - morley-prelude
      - morley
      - optparse-applicative
      - safe-exceptions
      - tzbtc

  tzbtc-client:
    main: Main.hs
    source-dirs: client

    dependencies:
      - morley-prelude
      - tzbtc

tests:
  tzbtc-test:
    <<: *test-common

    default-extensions:
      - DerivingStrategies

    dependencies:
    - bytestring
    - containers
    - hex-text
    - hspec
    - morley-prelude
    - morley
    - morley-ledgers
    - morley-ledgers-test
    - morley-upgradeable
    - mtl
    - optparse-applicative
    - tasty
    - tasty-hspec
    - tasty-hunit
    - tezos-bake-monitor-lib
    - text
    - tzbtc
    - universum
