# SPDX-FileCopyrightText: 2019 Bitcoin Suisse
#
# SPDX-License-Identifier: LicenseRef-Proprietary
#
<<: !include "./hpack/module.yaml"

name:                tzbtc
version:             0.1.0

extra-source-files:
- README.md
- CONTRIBUTING.md

category:            Blockchain
description: Wrapped Bitcoin on Tezos Blockchain

library:
  <<: *lib-common

  default-extensions:
    - DerivingStrategies
    - DeriveAnyClass
    - NoApplicativeDo

  dependencies:
    - aeson
    - aeson-casing
    - aeson-pretty
    - bytestring
    - containers
    - directory
    - hex-text
    - http-client
    - http-types
    - fmt
    - memory
    - morley
    - lorentz-contracts
    - morley-prelude
    - named
    - optparse-applicative
    - megaparsec
    - process
    - servant
    - servant-client
    - servant-client-core
    - singletons
    - text
    - tezos-bake-monitor-lib
    - universum
    - safe-exceptions
    - vector
    - vinyl
    - xdg-basedir

  when:
    - condition: os(linux)
      dependencies: editor-open

executables:
  tzbtc:
    <<: *exec-common

    dependencies:
      - fmt
      - lorentz-contracts
      - morley-prelude
      - morley
      - optparse-applicative
      - safe-exceptions
      - tzbtc

  tzbtc-client:
    main: Main.hs
    source-dirs: client

    dependencies:
      - fmt
      - morley
      - morley-prelude
      - optparse-applicative
      - tzbtc
      - vinyl

tests:
  tzbtc-test:
    <<: *test-common

    default-extensions:
      - DerivingStrategies

    dependencies:
    - aeson
    - tzbtc
    - morley-prelude
    - universum
    - tasty
    - tasty-hunit
    - tasty-hspec
    - morley
    - containers
    - lorentz-contracts
    - lorentz-contracts-test
    - tezos-bake-monitor-lib
    - bytestring
    - text
    - hex-text
    - hspec
