# SPDX-FileCopyrightText: 2019 Bitcoin Suisse
#
# SPDX-License-Identifier: LicenseRef-Proprietary
#
<<: !include "./hpack/module.yaml"

name:                tzbtc
version:             0.0.1

extra-source-files:
- README.md
- CONTRIBUTING.md

category:            Blockchain
description: Wrapped Bitcoin on Tezos Blockchain

library:
  <<: *lib-common

  default-extensions:
    - DerivingStrategies
    - DeriveAnyClass
    - NoApplicativeDo

  dependencies:
    - aeson
    - aeson-casing
    - bytestring
    - containers
    - directory
    - hex-text
    - http-client
    - fmt
    - memory
    - morley
    - lorentz-contracts
    - morley-prelude
    - named
    - optparse-applicative
    - megaparsec
    - process
    - servant
    - servant-client
    - servant-client-core
    - text
    - tezos-bake-monitor-lib
    - universum
    - safe-exceptions
    - vinyl
    - hex-text
    - bytestring
    - aeson
    - aeson-casing
    - singletons

executables:
  tzbtc:
    <<: *exec-common

    dependencies:
      - fmt
      - lorentz-contracts
      - morley-prelude
      - morley
      - optparse-applicative
      - safe-exceptions
      - tzbtc

  tzbtc-client:
    main: Main.hs
    source-dirs: client

    dependencies:
      - fmt
      - lorentz-contracts
      - morley-prelude
      - morley
      - optparse-applicative
      - safe-exceptions
      - tzbtc

tests:
  tzbtc-test:
    <<: *test-common

    default-extensions:
      - DerivingStrategies

    dependencies:
    - tzbtc
    - morley-prelude
    - universum
    - tasty
    - tasty-hunit
    - morley
    - fmt
    - bytestring
    - containers
    - singletons
    - lorentz-contracts
    - named
    - text
    - tezos-bake-monitor-lib
    - hex-text
    - hspec
    - attoparsec
    - text
    - temporary
    - typed-process
