# SPDX-FileCopyrightText: 2019 Bitcoin Suisse
#
# SPDX-License-Identifier: LicenseRef-Proprietary
#
<<: !include "./hpack/module.yaml"

name:                tzbtc
version:             0.0.1

extra-source-files:
- README.md
- CONTRIBUTING.md

category:            Blockchain
description: Wrapped Bitcoin on Tezos Blockchain

library:
  <<: *lib-common

  default-extensions:
    - DerivingStrategies
    - DeriveAnyClass
    - NoApplicativeDo

  dependencies:
    - containers
    - morley
    - lorentz-contracts
    - morley-prelude
    - named
    - fmt
    - text
    - universum
    - optparse-applicative
    - vinyl

executables:
  tzbtc:
    <<: *exec-common

    dependencies:
      - fmt
      - lens
      - lorentz-contracts
      - morley-prelude
      - morley
      - optparse-applicative
      - safe-exceptions
      - tzbtc
      #######
      - typed-process
      - bytestring
      - temporary
      - singletons
      - attoparsec
      - text

tests:
  tzbtc-test:
    <<: *test-common

    default-extensions:
      - DerivingStrategies

    dependencies:
    - tzbtc
    - morley-prelude
    - universum
    - tasty
    - tasty-hunit
    - morley
    - fmt
    - containers
    - singletons
    - lorentz-contracts
    - named
