# SPDX-FileCopyrightText: 2019 Bitcoin Suisse
#
# SPDX-License-Identifier: LicenseRef-MIT-BitcoinSuisse
#
# when updating git dependencies, please run
# nix run -f https://github.com/serokell/scratch/archive/master.tar.gz scripts.update-stack-shas -c update-stack-shas
resolver: lts-16.5

packages:
- .

extra-deps:
- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    9e69d52741e456bd0976a1ec4c45cc4c43a11722 # morley-1.11.1
  subdirs:
    - code/morley-client
    - code/cleveland

- git:
    https://gitlab.com/morley-framework/morley-multisig.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    98b927ec0660088947a3fe3e94e2076fcf8fe6ee # master

- git:
    https://gitlab.com/morley-framework/morley-ledgers.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    1a1f1caab12e051d0c930c2f9bde4b5a0bca1d60 # master
  subdirs:
    - code/morley-ledgers
    - code/morley-ledgers-test

- git:
    https://gitlab.com/morley-framework/morley-upgradeable.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    f72475818bcb434ccb20bbd9fea4143823ce5add # master

# Stable parts of morley available from Hackage
- morley-prelude-0.3.0
- tasty-hunit-compat-0.2
- morley-1.11.1
- lorentz-0.9.0
- indigo-0.5.0

# Required by morley
- show-type-0.1.1@sha256:24f681a3481b3f9630e619d816054804ba1bd6cc05b5978ddd2cece8499ff2fa
- base58-bytestring-0.1.0
- hex-text-0.1.0.0
- named-0.3.0.1@sha256:69b9722301201f8ed8abc89c4595e22c746e944bf4cdfafa8b21b14d336b26d1,2233
- vinyl-0.12.1@sha256:43456d4b3009646eee63953cbe539f1f4d0caf8bc3c25e841117e712836508f3,3790
- cryptonite-0.27
- git: https://github.com/int-index/caps.git
  commit: c5d61837eb358989b581ed82b1e79158c4823b1b
- uncaught-exception-0.1.0


nix:
  packages: [zlib]
