# SPDX-FileCopyrightText: 2019 Bitcoin Suisse
#
# SPDX-License-Identifier: LicenseRef-MIT-BitcoinSuisse
#
# when updating git dependencies, please run
# nix run -f https://github.com/serokell/scratch/archive/master.tar.gz scripts.update-stack-shas -c update-stack-shas
resolver: lts-17.3

packages:
- .

extra-deps:
- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    295bdad3f75d76e780ec0b64b5e2e3d8d8f41441 # morley-1.14.0
  subdirs:
    - code/cleveland
    - code/morley-client

- git:
    https://gitlab.com/morley-framework/morley-multisig.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    ef4dc069f46a07485446fe0346417484b33af86c # master

- git:
    https://gitlab.com/morley-framework/morley-ledgers.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    8e1ec4c161ee9c22e03c74dccb579634ced6165c # master
  subdirs:
    - code/morley-ledgers
    - code/morley-ledgers-test

- git:
    https://gitlab.com/morley-framework/morley-upgradeable.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    202ca74c708e2137f2c4e1adff527180d58edc14 # v0.3

- git:
    https://gitlab.com/morley-framework/indigo.git
  commit:
    1177ddb1390610c76b8a735c1fda2eacb2cbef6b # master
  subdirs:
    - .

# Stable parts of morley available from Hackage
- morley-1.14.0
- morley-prelude-0.4.0
- lorentz-0.11.0
- tasty-hunit-compat-0.2

# Required by morley
- hex-text-0.1.0.0
- named-0.3.0.1
- show-type-0.1.1
- summoner-2.0.1.1
- generic-data-0.8.3.0
- neat-interpolation-0.3.2.6
- megaparsec-8.0.0
- git: https://github.com/serokell/base-noprelude.git
  commit: 87df0899801dcdffd08ef7c3efd3c63e67e623c2
- git: https://github.com/serokell/galois-field.git
  commit: 576ba98ec947370835a1f308895037c7aa7f8b71
- git: https://github.com/int-index/caps.git
  commit: c5d61837eb358989b581ed82b1e79158c4823b1b
- git: https://github.com/serokell/elliptic-curve.git
  commit: b8a3d0cf8f7bacfed77dc3b697f5d08bd33396a8
- git: https://github.com/serokell/pairing.git
  commit: cf86cf1f6b03f478a439703b050c520a9d455353

nix:
  packages: [zlib]
