# SPDX-FileCopyrightText: 2019 Bitcoin Suisse
#
# SPDX-License-Identifier: LicenseRef-MIT-BitcoinSuisse
#
# when updating git dependencies, please run
# nix run -f https://github.com/serokell/scratch/archive/master.tar.gz scripts.update-stack-shas -c update-stack-shas
resolver: lts-17.3

packages:
- .

extra-deps:
- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    a726d42f89f83aa794f381b5332a542b634ba057 # morley-1.15.1
  subdirs:
    - code/cleveland
    - code/morley-client

- git:
    https://gitlab.com/morley-framework/morley-multisig.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    c2e041a8ab7ace0807e3c605e4bf60065cd6c9f1 # master

- git:
    https://gitlab.com/morley-framework/morley-ledgers.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    2c9c23d50b5cef62d71572573ea760a01b44d7cf # master
  subdirs:
    - code/morley-ledgers
    - code/morley-ledgers-test

- git:
    https://gitlab.com/morley-framework/morley-upgradeable.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    04ba4f962a5d4ab6580eaf8a08a4bab0259e4469 # master

- git:
    https://gitlab.com/morley-framework/indigo.git
  commit:
    3812248243e58ed7eae4579c777751fbe32f897a # master
  subdirs:
    - .

# Stable parts of morley available from Hackage
- morley-1.15.1
- morley-prelude-0.4.2
- lorentz-0.12.1
- tasty-hunit-compat-0.2

# Required by morley
- hex-text-0.1.0.0
- named-0.3.0.1
- show-type-0.1.1
- summoner-2.0.1.1
- generic-data-0.8.3.0
- neat-interpolation-0.3.2.6
- megaparsec-8.0.0
- tasty-1.4.1
- tasty-ant-xml-1.1.8
- git: https://github.com/serokell/base-noprelude.git
  commit: 87df0899801dcdffd08ef7c3efd3c63e67e623c2
- git: https://github.com/serokell/galois-field.git
  commit: 576ba98ec947370835a1f308895037c7aa7f8b71
- git: https://github.com/int-index/caps.git
  commit: c5d61837eb358989b581ed82b1e79158c4823b1b
- git: https://github.com/serokell/elliptic-curve.git
  commit: b8a3d0cf8f7bacfed77dc3b697f5d08bd33396a8
- git: https://github.com/serokell/pairing.git
  commit: cf86cf1f6b03f478a439703b050c520a9d455353

nix:
  packages: [zlib]
