# SPDX-FileCopyrightText: 2019 Bitcoin Suisse
# SPDX-License-Identifier: LicenseRef-Proprietary

env:
  NIX_PATH: nixpkgs=https://github.com/nixos/nixpkgs/archive/b640dbd00877f51616750e347a32fbcb49d2968c.tar.gz

steps:
 - command: nix run nixpkgs.{gnumake,hlint,ncurses} -c make lint
   label: make lint
 - command: nix run nixpkgs.reuse -c reuse lint
   label: reuse lint
 - command: .buildkite/check-trailing-whitespace.sh
 - command: "nix run -f https://github.com/serokell/crossref-verifier/archive/master.tar.gz -c crossref-verify"
   label: crossref-verify
   soft_fail: true
 - commands:
   - nix-shell --run "make test-ci"
   - echo +++ Weeder
   - nix-shell --run "nix run nixpkgs.haskellPackages.weeder -c weeder ."
   - echo +++ Bats
   - nix-shell --run "nix run nixpkgs.bats -c bats test.bats"
   - echo 'bats passed successfully'
   - echo +++ Smoke
   - nix-shell --run "nix run nixpkgs.python3 -c bash scripts/ci-test.sh"
   - echo 'ci-test passed successfully'
   label: test && weeder && bats
