# SPDX-FileCopyrightText: 2019 Bitcoin Suisse
# SPDX-License-Identifier: LicenseRef-Proprietary

env:
  NIX_PATH: nixpkgs=channel:nixos-unstable
  test_step: "test && weeder && bats"
  crossref_verify: "nix run -f https://github.com/serokell/crossref-verifier/archive/f97ded8356e5afe4d3ebdeaccd4eed504bb99b0f.tar.gz -c crossref-verify --mode local-only"

steps:
  - label: make lint
    branches: "!autodoc/master"
    command: nix run nixpkgs.{gnumake,hlint,ncurses} -c make lint

  - label: reuse lint
    branches: "!autodoc/master"
    command: nix run nixpkgs.reuse -c reuse lint

  - label: check trailing whitespace
    branches: "!autodoc/master"
    command: .buildkite/check-trailing-whitespace.sh

  - label: crossref-verify
    branches: "!autodoc/master"
    command: nix-shell --run "${crossref_verify} --config ./.crossref-verifier.yaml"
    soft_fail: true  # TODO: remove

  - label: ${test_step}
    branches: "!autodoc/master"
    commands:
    - nix-shell --run "make test-ci"
    - echo +++ Weeder
    - nix-shell --run "nix run nixpkgs.haskellPackages.weeder -c weeder ."
    - echo +++ Bats
    - nix-shell --run "nix run nixpkgs.bats -c bats bats/*.bats"
    - echo 'bats passed successfully'
    - nix-shell --run "stack exec tzbtc printContractDoc > TZBTC-contract.md"
    artifact_paths:
      - "TZBTC-contract.md"

  - label: crossref-verify generated doc
    branches: "!autodoc/master"
    commands:
    - nix-shell --run "mkdir tmp"
    - nix-shell --run "buildkite-agent artifact download TZBTC-contract.md tmp/ --step \"${test_step}\""
    - nix-shell --run "${crossref_verify} --config ./.crossref-verifier.yaml --root tmp"
    soft_fail: true  # TODO: remove

  - label: autodoc upload
    branches: master
    commands:
    - nix-shell --run "mkdir tmp"
    - nix-shell --run "buildkite-agent artifact download TZBTC-contract.md tmp/ --step \"${test_step}\""
    - ./scripts/ci/upload-autodoc.sh

  - label: patched tezos-client building
    branches: "!autodoc/master"
    commands:
    - nix-build release.nix -A tezos-client -o tezos-client
    artifact_paths:
      - ./tezos-client/*

  - label: packaging
    branches: "!autodoc/master"
    commands:
    - nix-build release.nix -A static -o tzbtc-static
    - nix-build release.nix -A deb -o tzbtc-client-deb
    - nix-build release.nix -A rpm -o tzbtc-client-rpm
    artifact_paths:
      - ./tzbtc-static/bin/tzbtc-client
      - ./tzbtc-client-deb/*
      - ./tzbtc-client-rpm/*
